device: cpu
dataset: uit-vsfc
encoder: bert
epochs: 10
batch_size: 2
feature_shape: 768
num_classes: 3
max_length: 512
tokenizer_type: bert-base-multilingual-cased
num_workers: 4
learning_rate: 0.001
momentum: 0.9