device: cuda
dataset: aivivn
encoder: phobert
epochs: 10
batch_size: 2
feature_shape: 768
num_classes: 2
pivot: 0.8
max_length: 256
tokenizer_type: phobert
num_workers: 4
learning_rate: 3e-5
momentum: 0.9
random_seed: 101
accumulation_steps: 5
pretrained: outputs/phobert_aivivn/checkpoints/checkpoint_best.vndee