device: cpu
dataset: aivivn
encoder: phobert
epochs: 10
batch_size: 2
feature_shape: 768
num_classes: 2
pivot: 0.8
max_length: 512
tokenizer_type: phobert
num_workers: 4
learning_rate: 0.001
momentum: 0.9